### ISSUE TITLE
Update the Gnome Bug Triage wiki

### ISSUE THREAD

**Issue by tassia** [tassia/vanierFLOSS#13]
The Gnome Bug Triage wiki [1] needs to be updated. The page was last-edited in 2010, so there might be quite a few things to get fixed. Here is the first one: the reference and link to Bugzilla [2] should be updated to the new Gnome gitlab [3].

If you take this issue at hands, please start reading as a new contributor who wants to bug triage for Gnome in Debian and any time you find an inconsistency with the documentation, either fix it, or talk to people on IRC to check if you really spotted a bug or not.

To work on this bug you need to:
1. Have an account on the Debian wiki [4], or create one
2. Read the wiki and identify outdated info, or improve the content somehow
3. If you need to talk to the team, connect to the IRC channel (OFTC #debian-gnome). Feel free to talk to me on the Discord if you need a helping hand with IRC.

[1] https://wiki.debian.org/Gnome/BugTriage
[2] https://bugzilla.gnome.org/createaccount.cgi
[3] https://gitlab.gnome.org/GNOME
[4] https://wiki.debian.org

**Comment by gbouzon** [comment]
done!
