### ISSUE TITLE
Debian live: Vanier custom

### ISSUE THREAD

**Issue by araujotassia** [tassia/vanierFLOSS#9]
Create a Debian live image with a selection of packages that are mostly useful for Vanier students, customize grub and desktop to feature Vanier and club identities.

**Comment by gbouzon** [comment]
Started the creation of VanierOS (debian-based live system):
Building it using eznix packages (https://sourceforge.net/projects/eznixos/) and xfce (lightweight). 
Repository:  https://github.com/gbouzon/vanierOS
Licensed under GNU General Public License v3.0

**Comment by tassia** [comment]
This project was completed and released by the end of 2021, closing the issue.
